/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paplicacion;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author numbe
 */
public class JuegoClasificacion extends javax.swing.JFrame {

    public Timer tiempo;
    public int centesimas_segundos = 0;
    public int segundos = 0;
    public int minutos = 0;
    public int horas = 0;
    
    CJCcorreoelectronico c = new CJCcorreoelectronico();
    CRegistro d = new CRegistro();
    CJuegoClasificaccion objeto = new CJuegoClasificaccion();
    private ActionListener acciones = new ActionListener(){
       
        @Override
        public void actionPerformed(ActionEvent ae) {
       
            centesimas_segundos ++;
            if (centesimas_segundos == 100) {
                segundos ++;
                centesimas_segundos =0;
            }
            if (segundos == 60) {
                minutos ++;
                segundos = 0;
            }
            if (minutos == 60) {
                horas ++;
                minutos =0;
            }
            if (horas==24) {
                horas =0;
            }
            
            actualizarEtiquetaTiempo();
        }
    };
    
    private void actualizarEtiquetaTiempo(){
    String texto = (horas<=9?"0":"")+horas+":"+(minutos<=9?"0":"")+minutos+":"+(segundos<=9?"0":"")+segundos+":"+(centesimas_segundos <=9?"0":"")+centesimas_segundos;
    ctiempo.setText(texto);
    }
    
    public JuegoClasificacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        inicializar();
        tiempo = new Timer(10, acciones);
    }
     ImageIcon icono = new ImageIcon("src/Imagenes/A6.png");
    private void inicializar() {
   ImageIcon icono = new ImageIcon("src/Imagenes/A5.png");
    this.setIconImage(icono.getImage());
    }
   

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ctiempo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Bp = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Bd = new javax.swing.JButton();
        labeliniciar = new javax.swing.JLabel();
        Bi = new javax.swing.JButton();
        Br = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        NM6 = new javax.swing.JTextField();
        NM1 = new javax.swing.JTextField();
        NM2 = new javax.swing.JTextField();
        NM3 = new javax.swing.JTextField();
        NM4 = new javax.swing.JTextField();
        NM5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        G1 = new javax.swing.JTextField();
        G2 = new javax.swing.JTextField();
        G3 = new javax.swing.JTextField();
        G4 = new javax.swing.JTextField();
        G5 = new javax.swing.JTextField();
        G6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        M1 = new javax.swing.JTextField();
        M2 = new javax.swing.JTextField();
        M3 = new javax.swing.JTextField();
        M4 = new javax.swing.JTextField();
        M5 = new javax.swing.JTextField();
        M6 = new javax.swing.JTextField();
        Br1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        labeliniciar1 = new javax.swing.JLabel();
        Bd1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ayuda");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 640, 70, 20));

        ctiempo.setFont(new java.awt.Font("Felix Titling", 1, 36)); // NOI18N
        ctiempo.setForeground(new java.awt.Color(255, 255, 255));
        ctiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ctiempo.setText("00:00:00:00");
        jPanel1.add(ctiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 230, 40));

        jLabel2.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("pausar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 70, 20));

        jLabel3.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REVISAR");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 640, 70, 20));

        Bp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B.png"))); // NOI18N
        Bp.setBorder(null);
        Bp.setBorderPainted(false);
        Bp.setContentAreaFilled(false);
        Bp.setEnabled(false);
        Bp.setFocusPainted(false);
        Bp.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B.png"))); // NOI18N
        Bp.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B.png"))); // NOI18N
        Bp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BpActionPerformed(evt);
            }
        });
        jPanel1.add(Bp, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 160, 60));

        jLabel5.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("46");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, 30, 30));

        jLabel6.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("detener");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 80, 20));

        Bd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B.png"))); // NOI18N
        Bd.setBorder(null);
        Bd.setBorderPainted(false);
        Bd.setContentAreaFilled(false);
        Bd.setEnabled(false);
        Bd.setFocusPainted(false);
        Bd.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B.png"))); // NOI18N
        Bd.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B.png"))); // NOI18N
        Bd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdActionPerformed(evt);
            }
        });
        jPanel1.add(Bd, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 160, 60));

        labeliniciar.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        labeliniciar.setForeground(new java.awt.Color(0, 0, 0));
        labeliniciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labeliniciar.setText("iniciar");
        jPanel1.add(labeliniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 130, 20));

        Bi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B.png"))); // NOI18N
        Bi.setBorder(null);
        Bi.setBorderPainted(false);
        Bi.setContentAreaFilled(false);
        Bi.setFocusPainted(false);
        Bi.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B.png"))); // NOI18N
        Bi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B.png"))); // NOI18N
        Bi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BiActionPerformed(evt);
            }
        });
        jPanel1.add(Bi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 160, 60));

        Br.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B.png"))); // NOI18N
        Br.setBorder(null);
        Br.setBorderPainted(false);
        Br.setContentAreaFilled(false);
        Br.setFocusPainted(false);
        Br.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B.png"))); // NOI18N
        Br.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B.png"))); // NOI18N
        Br.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrActionPerformed(evt);
            }
        });
        jPanel1.add(Br, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 160, 60));

        jLabel7.setFont(new java.awt.Font("Felix Titling", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Juego por clasificacion");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 550, 47));

        NM6.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        NM6.setEnabled(false);
        jPanel1.add(NM6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 170, -1));

        NM1.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        NM1.setEnabled(false);
        jPanel1.add(NM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 170, -1));

        NM2.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        NM2.setEnabled(false);
        jPanel1.add(NM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 170, -1));

        NM3.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        NM3.setEnabled(false);
        jPanel1.add(NM3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 170, -1));

        NM4.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        NM4.setEnabled(false);
        jPanel1.add(NM4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 170, -1));

        NM5.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        NM5.setEnabled(false);
        jPanel1.add(NM5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 170, -1));

        jLabel8.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Gases nobles");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 210, 30));

        G1.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        G1.setEnabled(false);
        jPanel1.add(G1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 170, -1));

        G2.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        G2.setEnabled(false);
        jPanel1.add(G2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 170, -1));

        G3.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        G3.setEnabled(false);
        jPanel1.add(G3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 170, -1));

        G4.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        G4.setEnabled(false);
        jPanel1.add(G4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 170, -1));

        G5.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        G5.setEnabled(false);
        jPanel1.add(G5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 170, -1));

        G6.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        G6.setEnabled(false);
        jPanel1.add(G6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 170, -1));

        jLabel9.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("metales");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 170, 30));

        M1.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        M1.setEnabled(false);
        jPanel1.add(M1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 170, -1));

        M2.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        M2.setEnabled(false);
        jPanel1.add(M2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 170, -1));

        M3.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        M3.setEnabled(false);
        jPanel1.add(M3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 170, -1));

        M4.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        M4.setEnabled(false);
        jPanel1.add(M4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 170, -1));

        M5.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        M5.setEnabled(false);
        jPanel1.add(M5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, 170, -1));

        M6.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        M6.setEnabled(false);
        jPanel1.add(M6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 170, -1));

        Br1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B.png"))); // NOI18N
        Br1.setBorder(null);
        Br1.setBorderPainted(false);
        Br1.setContentAreaFilled(false);
        Br1.setFocusPainted(false);
        Br1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B.png"))); // NOI18N
        Br1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B.png"))); // NOI18N
        Br1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Br1ActionPerformed(evt);
            }
        });
        jPanel1.add(Br1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 620, 160, 60));

        jLabel10.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("No Metales");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 170, 30));

        jLabel11.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("79");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 30, 30));

        jLabel12.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("47");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, 30, 30));

        jLabel13.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("22");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 30, 30));

        jLabel14.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("11");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 30, 30));

        jLabel15.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("88");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 30, 30));

        jLabel16.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("86");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 30, 30));

        jLabel17.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("2");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 30, 30));

        jLabel18.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("36");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 30, 30));

        jLabel19.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("10");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 30, 30));

        jLabel20.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("54");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 30, 30));

        jLabel21.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("18");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 30, 30));

        jLabel22.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("53");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 30, 30));

        jLabel23.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("7");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 30, 30));

        jLabel24.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("9");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 30, 30));

        jLabel25.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("17");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 30, 30));

        jLabel26.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("8");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 30, 30));

        jLabel27.setFont(new java.awt.Font("Felix Titling", 1, 20)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("35");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, 30, 30));

        labeliniciar1.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        labeliniciar1.setForeground(new java.awt.Color(0, 0, 0));
        labeliniciar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labeliniciar1.setText("HOME");
        jPanel1.add(labeliniciar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, 20));

        Bd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B.png"))); // NOI18N
        Bd1.setBorder(null);
        Bd1.setBorderPainted(false);
        Bd1.setContentAreaFilled(false);
        Bd1.setFocusPainted(false);
        Bd1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B.png"))); // NOI18N
        Bd1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B.png"))); // NOI18N
        Bd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bd1ActionPerformed(evt);
            }
        });
        jPanel1.add(Bd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void enviarCorreo(){
       c.setContracena("yoyitojuan");
       c.setUsuarioCorreo("juanjesusgarciamaturana@gmail.com");
       c.setAdjunto("Equipo Atom");
       c.setMensaje(d.nickname + " Tenemos tus resultados!!!\n" + "\n" + "Especialidad: QUIMICA\n" + "\n" + "Modo de juego: JUEGO POR CLASIFICACION\n" + "\n"  + "Aciertos: " + objeto.ContadorBuenas +" / 18" + "\n" + "\n"
               + "Tiempo: " + Integer.toString(horas) + ":" + Integer.toString(minutos) + ":" + Integer.toString(segundos) + ":" + Integer.toString(centesimas_segundos) + "\n" + "\n"
       + " El Equipo de Atom espera que te haya gustado el juego y que sigas mejorando tu puntaje.\n" + "\n" + " Por cierto... " + objeto.Mensaje);
       c.setDestino(d.correo);
       c.setNombreArchivo("15.png");
       c.setRutaArchivo("src/Imagenes/A5.png");
       CJCcontrolador co = new CJCcontrolador();
        if (co.enviarcorreo(c)) {
            JOptionPane.showMessageDialog(null,"Tus resultados fueron enviados\n a tu correo electronico.\n Corre a verlos!!!\n", "Correo Enviado",JOptionPane.PLAIN_MESSAGE, this.icono);
            
        }else{JOptionPane.showMessageDialog(null, "Tus resultados no fueron enviados\n a tu correo electronico.","Correo No Enviado",JOptionPane.PLAIN_MESSAGE, this.icono);}
    }
    
    
    
    
    private void BpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpActionPerformed
        // BOTON PAUSAR
        tiempo.stop();
        Bi.setEnabled(true);
    }//GEN-LAST:event_BpActionPerformed

    private void BrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrActionPerformed
        // Boton REVISAR
        CJuegoClasificaccion objeto = new CJuegoClasificaccion();
        
        tiempo.stop();
        
        objeto.Gases[0][1] = G1.getText(); objeto.Gases[1][1] = G2.getText(); objeto.Gases[2][1] = G3.getText();
        objeto.Gases[3][1] = G4.getText(); objeto.Gases[4][1] = G5.getText(); objeto.Gases[5][1] = G6.getText();
        
        objeto.NMETALES[0][1] = NM1.getText(); objeto.NMETALES[1][1] = NM2.getText(); objeto.NMETALES[2][1] = NM3.getText();
        objeto.NMETALES[3][1] = NM4.getText(); objeto.NMETALES[4][1] = NM5.getText(); objeto.NMETALES[5][1] = NM6.getText();
        
        objeto.METALES[0][1] = M1.getText(); objeto.METALES[1][1] = M2.getText(); objeto.METALES[2][1] = M3.getText();
        objeto.METALES[3][1] = M4.getText(); objeto.METALES[4][1] = M5.getText(); objeto.METALES[5][1] = M6.getText();
        
        objeto.comparaGases();
        objeto.comparaNometales();
        objeto.comparaMetales();
        objeto.mensaje();
        
        JOptionPane.showMessageDialog(null, objeto.Mensaje,"Correo Enviado",JOptionPane.PLAIN_MESSAGE, this.icono);
        enviarCorreo();
    }//GEN-LAST:event_BrActionPerformed

    private void BiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BiActionPerformed
        // Boton INICIAR
        tiempo.start();
        Bi.setEnabled(false);
        labeliniciar.setText("Reanudar");
        Bd.setEnabled(true);
        Bp.setEnabled(true);
        
        
        G1.setEnabled(true); G2.setEnabled(true); G3.setEnabled(true); 
        G4.setEnabled(true); G5.setEnabled(true); G6.setEnabled(true);
        
        NM1.setEnabled(true); NM2.setEnabled(true); NM3.setEnabled(true);
        NM4.setEnabled(true); NM5.setEnabled(true); NM6.setEnabled(true);
        
        M1.setEnabled(true); M2.setEnabled(true); M3.setEnabled(true);
        M4.setEnabled(true); M5.setEnabled(true); M6.setEnabled(true);
        
    }//GEN-LAST:event_BiActionPerformed

    private void BdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdActionPerformed
        // Boton DETENER
         if (tiempo.isRunning()) {
            tiempo.stop();
            
        }
         
        centesimas_segundos = 0;
        segundos = 0;
        minutos = 0;
        horas = 0;
          
        actualizarEtiquetaTiempo(); 
        Bi.setEnabled(true);
        Bp.setEnabled(false);
        Bd.setEnabled(false);
        labeliniciar.setText("Iniciar");
        
       
    }//GEN-LAST:event_BdActionPerformed

    private void Br1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Br1ActionPerformed
        // AYUDA
        JOptionPane.showMessageDialog(null, " AJA!!! \n Que dijiste, pos ya mas facil no? \n Orele no sea tramposo. \n !A JUGAR!","Nosotros te ayudamos",JOptionPane.PLAIN_MESSAGE, this.icono);
    }//GEN-LAST:event_Br1ActionPerformed

    private void Bd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bd1ActionPerformed
        // Boton DETENER
        Sounds c = new Sounds();
        SeleccionQYF objeto = new SeleccionQYF();
        if (tiempo.isRunning()) {
            tiempo.stop();

        }

        centesimas_segundos = 0;
        segundos = 0;
        minutos = 0;
        horas = 0;

        actualizarEtiquetaTiempo();
        Bi.setEnabled(true);
        Bp.setEnabled(false);
        Bd.setEnabled(false);
        labeliniciar.setText("Iniciar");

        this.setVisible(false);
        objeto.setVisible(true);
        c.SoundQ1.stop();
        c.sonidoMenu();
    }//GEN-LAST:event_Bd1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoClasificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoClasificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoClasificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoClasificacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoClasificacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bd;
    private javax.swing.JButton Bd1;
    private javax.swing.JButton Bi;
    private javax.swing.JButton Bp;
    private javax.swing.JButton Br;
    private javax.swing.JButton Br1;
    private javax.swing.JTextField G1;
    private javax.swing.JTextField G2;
    private javax.swing.JTextField G3;
    private javax.swing.JTextField G4;
    private javax.swing.JTextField G5;
    private javax.swing.JTextField G6;
    private javax.swing.JTextField M1;
    private javax.swing.JTextField M2;
    private javax.swing.JTextField M3;
    private javax.swing.JTextField M4;
    private javax.swing.JTextField M5;
    private javax.swing.JTextField M6;
    private javax.swing.JTextField NM1;
    private javax.swing.JTextField NM2;
    private javax.swing.JTextField NM3;
    private javax.swing.JTextField NM4;
    private javax.swing.JTextField NM5;
    private javax.swing.JTextField NM6;
    private javax.swing.JLabel ctiempo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labeliniciar;
    private javax.swing.JLabel labeliniciar1;
    // End of variables declaration//GEN-END:variables
}
