/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paplicacion;

import java.sql.*;
import com.mysql.jdbc.Connection;
import java.applet.AudioClip;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.mail.internet.AddressException;
import java.util.Properties;
import javax.activation.DataHandler;
import javax.activation.FileDataSource;
import javax.mail.BodyPart;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author numbe
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    Sounds m = new Sounds();
    
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
       // setIconImage(new ImageIcon(getClass().getResource("/src/Imagenes/AtomoI.png")).getImage());
       inicializar();
        m.sonidoMenu();
    }
    
    
    
    ImageIcon icono = new ImageIcon("src/Imagenes/A6.png");
    private void inicializar() {
    ImageIcon icono = new ImageIcon("src/Imagenes/A5.png");
    ImageIcon t;
    this.setIconImage(icono.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        apellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        apodo = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BG1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        contra = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRO DE USUARIO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 60, 480, 47));

        nombre.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 336, 47));

        jLabel2.setFont(new java.awt.Font("Felix Titling", 1, 21)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 138, 47));

        jLabel3.setFont(new java.awt.Font("Felix Titling", 1, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Apellido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 138, 47));

        apellido.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jPanel1.add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 336, 47));

        jLabel4.setFont(new java.awt.Font("Felix Titling", 1, 21)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nickname");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 138, 47));

        apodo.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jPanel1.add(apodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 336, 47));

        correo.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jPanel1.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 336, 47));

        jLabel5.setFont(new java.awt.Font("Felix Titling", 1, 19)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Guardar");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 640, 110, 30));

        BG1.setFont(new java.awt.Font("Felix Titling", 1, 21)); // NOI18N
        BG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B.png"))); // NOI18N
        BG1.setBorder(null);
        BG1.setBorderPainted(false);
        BG1.setContentAreaFilled(false);
        BG1.setFocusPainted(false);
        BG1.setFocusable(false);
        BG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BG1ActionPerformed(evt);
            }
        });
        jPanel1.add(BG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 630, -1, -1));

        jLabel7.setFont(new java.awt.Font("Felix Titling", 1, 21)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Contraseña");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 160, 47));

        jLabel8.setFont(new java.awt.Font("Felix Titling", 1, 21)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Email");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 138, 47));

        contra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 340, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        jLabel6.setFocusable(false);
        jLabel6.setInheritsPopupMenu(false);
        jLabel6.setRequestFocusEnabled(false);
        jLabel6.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 600, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    ConexionBD con = new ConexionBD();
    Connection cn = (Connection) con.conexion();
    
    
    private void BG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BG1ActionPerformed
        // Boton Guardar

        CRegistro objeto = new CRegistro();
        SeleccionQYF SQ = new SeleccionQYF();
        
        
        objeto.nombre = nombre.getText();
        objeto.apellido = apellido.getText();
        objeto.nickname = apodo.getText();
        objeto.correo = correo.getText();
        objeto.contra = contra.getText();
        
        if (objeto.nombre.equals("")  || objeto.apellido.equals("") || objeto.nickname.equals("")|| objeto.correo.equals("")) {
            JOptionPane.showMessageDialog(null, "Faltan campos por llenar","Datos No Guardados",JOptionPane.PLAIN_MESSAGE, this.icono);
        }
        else{JOptionPane.showMessageDialog(null, "Datos guardados con exito", "Datos Guardados",JOptionPane.PLAIN_MESSAGE, this.icono );
        this.setVisible(false);
        SQ.setVisible(true);
        
        }
      
        try{
          PreparedStatement pps = cn.prepareStatement("INSERT INTO Usuario(Nickname,Email,contrasena) VALUES(?,?,?)");
             pps.setString(1, apodo.getText());
             pps.setString(2, correo.getText());
             pps.setString(3, contra.getText());
             pps.executeUpdate();
             JOptionPane.showMessageDialog(null,"Bien");
        }catch(SQLException ex){
            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null,ex);
        }
     
    }//GEN-LAST:event_BG1ActionPerformed

   
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BG1;
    private javax.swing.JTextField apellido;
    private javax.swing.JTextField apodo;
    private javax.swing.JPasswordField contra;
    private javax.swing.JTextField correo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
